plugins {
    id 'net.neoforged.moddev' version '1.0.19'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}



repositories {
    mavenLocal()
    maven {
        url 'https://maven.blakesmods.com'
    }
    maven {
        // saps.dev Maven (KubeJS and Rhino)
        url = "https://maven.saps.dev/minecraft"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
    maven {
        url = "https://maven.latvian.dev/releases"
    }
    maven {
        url 'https://jitpack.io'
        content {
            includeGroup "com.github.rtyley"
        }
    }
}

sourceSets {
    api
}

dependencies {
    implementation sourceSets.api.output


    implementation "com.blakebr0.cucumber:Cucumber:${cucumber_version}"
    implementation "com.blakebr0.mysticalagriculture:MysticalAgriculture:${cucumber_version}"
    implementation(accessTransformers(interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")))
}

test {
    useJUnitPlatform()
}


neoForge {

        accessTransformers {
            file('src/main/resources/META-INF/accesstransformer.cfg')
        }

    version = project.neoforge_version
    addModdingDependenciesTo(sourceSets.api)

    // interfaceInjectionData = files("interfaces.json")

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
        client {
            client()
        }
        client2 {
            client()
            programArguments.addAll('--username', 'Dev2')
        }
        data {
            data()
        }
        server {
            server()
        }
        apitest {
            client()
            sourceSet = sourceSets.api
        }
    }

    mods {

    }

    neoFormRuntime {
        useEclipseCompiler = true
        // enableCache = false
        // verbose = true

        additionalResults.put('vanillaDeobfuscated', project.file('build/vanilla.jar'))
    }

    parchment {
        minecraftVersion = "1.21"
        mappingsVersion = "2024.06.23"
    }


}