modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"


issueTrackerURL="https://github.com/Bluemethyst/ToolsJS/issues"

[[mods]]
modId = "toolsjs"
version = "0.0.1-1.20.1"
displayName = "ToolsJS"
credits="Thanks to FooterMan for the KubeJS Addon Template! And making this mod possible!"
authors="Bluemethyst"
description = '''
ToolsJS, addon for KubeJS for adding lots of misc tools. Thats it.
'''

[[dependencies.toolsjs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolsjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toolsjs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
