modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"


issueTrackerURL="https://github.com/Bluemethyst/CucumberJS/issues"

[[mods]]
modId = "cucumberjs"
version = "0.0.1-1.20.1"
displayName = "CucumberJS"
credits="Thanks to FooterMan for the KubeJS Addon Template! And making this mod possible!"
authors="Bluemethyst"
description = '''
CucumberJS, addon for KubeJS for adding lots of misc tools using Cucumber Library. Thats it.
'''

[[dependencies.cucumberjs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cucumberjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cucumberjs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
